<a href="https://colab.research.google.com/github/Qalb-e-Momin777/Practices/blob/main/Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a random tensor with shape (7, 7).


In [3]:
import torch
shape = torch.rand(7,7)
shape

tensor([[0.5427, 0.7181, 0.0024, 0.1395, 0.7264, 0.9872, 0.9623],
        [0.3319, 0.8972, 0.6200, 0.0579, 0.2176, 0.2016, 0.0374],
        [0.7287, 0.6365, 0.8837, 0.4190, 0.7885, 0.1968, 0.7608],
        [0.6672, 0.5607, 0.5915, 0.5178, 0.6648, 0.1989, 0.7740],
        [0.8148, 0.3537, 0.9406, 0.1139, 0.8003, 0.9786, 0.3308],
        [0.1664, 0.4789, 0.6608, 0.9908, 0.4536, 0.4727, 0.8858],
        [0.8766, 0.1068, 0.0738, 0.6304, 0.5744, 0.8887, 0.0212]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [10]:
tensor_2 = torch.rand(1,7)
torch.matmul(shape,tensor_2.T)

tensor([[2.6121],
        [0.9311],
        [2.3545],
        [2.1793],
        [2.5619],
        [2.4631],
        [1.9985]])

Set the random seed to 0 and do exercises 2 & 3 over again.

In [14]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
shape = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
print(shape == tensor)

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])
